//------------------------------------------------------------------------
// Copyright(c) 2023 redetach.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"DelayDemo.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"DelayDemo VST3 (64Bit)"
#else
#define stringFileDescription	"DelayDemo VST3"
#endif
#define stringCompanyName		"redetach\0"
#define stringLegalCopyright	"Copyright(c) 2023 redetach."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
