//------------------------------------------------------------------------
// Copyright(c) 2023 Rolin Blake.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Fuzz.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Fuzz VST3 (64Bit)"
#else
#define stringFileDescription	"Fuzz VST3"
#endif
#define stringCompanyName		"Rolin Blake\0"
#define stringLegalCopyright	"Copyright(c) 2023 Rolin Blake."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
